// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2l/go-hwc/internal/data/ent/cpu"
	"github.com/menta2l/go-hwc/internal/data/ent/host"
	"github.com/menta2l/go-hwc/internal/data/ent/predicate"
)

// CPUUpdate is the builder for updating Cpu entities.
type CPUUpdate struct {
	config
	hooks    []Hook
	mutation *CPUMutation
}

// Where appends a list predicates to the CPUUpdate builder.
func (cu *CPUUpdate) Where(ps ...predicate.Cpu) *CPUUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetVendorID sets the "vendor_id" field.
func (cu *CPUUpdate) SetVendorID(s string) *CPUUpdate {
	cu.mutation.SetVendorID(s)
	return cu
}

// SetFamily sets the "family" field.
func (cu *CPUUpdate) SetFamily(s string) *CPUUpdate {
	cu.mutation.SetFamily(s)
	return cu
}

// SetModel sets the "model" field.
func (cu *CPUUpdate) SetModel(s string) *CPUUpdate {
	cu.mutation.SetModel(s)
	return cu
}

// SetModelName sets the "model_name" field.
func (cu *CPUUpdate) SetModelName(s string) *CPUUpdate {
	cu.mutation.SetModelName(s)
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CPUUpdate) SetCreatedAt(t time.Time) *CPUUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CPUUpdate) SetNillableCreatedAt(t *time.Time) *CPUUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CPUUpdate) SetUpdatedAt(t time.Time) *CPUUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cu *CPUUpdate) SetNillableUpdatedAt(t *time.Time) *CPUUpdate {
	if t != nil {
		cu.SetUpdatedAt(*t)
	}
	return cu
}

// SetHostIDID sets the "host_id" edge to the Host entity by ID.
func (cu *CPUUpdate) SetHostIDID(id string) *CPUUpdate {
	cu.mutation.SetHostIDID(id)
	return cu
}

// SetNillableHostIDID sets the "host_id" edge to the Host entity by ID if the given value is not nil.
func (cu *CPUUpdate) SetNillableHostIDID(id *string) *CPUUpdate {
	if id != nil {
		cu = cu.SetHostIDID(*id)
	}
	return cu
}

// SetHostID sets the "host_id" edge to the Host entity.
func (cu *CPUUpdate) SetHostID(h *Host) *CPUUpdate {
	return cu.SetHostIDID(h.ID)
}

// Mutation returns the CPUMutation object of the builder.
func (cu *CPUUpdate) Mutation() *CPUMutation {
	return cu.mutation
}

// ClearHostID clears the "host_id" edge to the Host entity.
func (cu *CPUUpdate) ClearHostID() *CPUUpdate {
	cu.mutation.ClearHostID()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CPUUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CPUMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CPUUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CPUUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CPUUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CPUUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cpu.Table,
			Columns: cpu.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cpu.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.VendorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldVendorID,
		})
	}
	if value, ok := cu.mutation.Family(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldFamily,
		})
	}
	if value, ok := cu.mutation.Model(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldModel,
		})
	}
	if value, ok := cu.mutation.ModelName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldModelName,
		})
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: cpu.FieldCreatedAt,
		})
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: cpu.FieldUpdatedAt,
		})
	}
	if cu.mutation.HostIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cpu.HostIDTable,
			Columns: []string{cpu.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.HostIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cpu.HostIDTable,
			Columns: []string{cpu.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cpu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CPUUpdateOne is the builder for updating a single Cpu entity.
type CPUUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CPUMutation
}

// SetVendorID sets the "vendor_id" field.
func (cuo *CPUUpdateOne) SetVendorID(s string) *CPUUpdateOne {
	cuo.mutation.SetVendorID(s)
	return cuo
}

// SetFamily sets the "family" field.
func (cuo *CPUUpdateOne) SetFamily(s string) *CPUUpdateOne {
	cuo.mutation.SetFamily(s)
	return cuo
}

// SetModel sets the "model" field.
func (cuo *CPUUpdateOne) SetModel(s string) *CPUUpdateOne {
	cuo.mutation.SetModel(s)
	return cuo
}

// SetModelName sets the "model_name" field.
func (cuo *CPUUpdateOne) SetModelName(s string) *CPUUpdateOne {
	cuo.mutation.SetModelName(s)
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CPUUpdateOne) SetCreatedAt(t time.Time) *CPUUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CPUUpdateOne) SetNillableCreatedAt(t *time.Time) *CPUUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CPUUpdateOne) SetUpdatedAt(t time.Time) *CPUUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuo *CPUUpdateOne) SetNillableUpdatedAt(t *time.Time) *CPUUpdateOne {
	if t != nil {
		cuo.SetUpdatedAt(*t)
	}
	return cuo
}

// SetHostIDID sets the "host_id" edge to the Host entity by ID.
func (cuo *CPUUpdateOne) SetHostIDID(id string) *CPUUpdateOne {
	cuo.mutation.SetHostIDID(id)
	return cuo
}

// SetNillableHostIDID sets the "host_id" edge to the Host entity by ID if the given value is not nil.
func (cuo *CPUUpdateOne) SetNillableHostIDID(id *string) *CPUUpdateOne {
	if id != nil {
		cuo = cuo.SetHostIDID(*id)
	}
	return cuo
}

// SetHostID sets the "host_id" edge to the Host entity.
func (cuo *CPUUpdateOne) SetHostID(h *Host) *CPUUpdateOne {
	return cuo.SetHostIDID(h.ID)
}

// Mutation returns the CPUMutation object of the builder.
func (cuo *CPUUpdateOne) Mutation() *CPUMutation {
	return cuo.mutation
}

// ClearHostID clears the "host_id" edge to the Host entity.
func (cuo *CPUUpdateOne) ClearHostID() *CPUUpdateOne {
	cuo.mutation.ClearHostID()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CPUUpdateOne) Select(field string, fields ...string) *CPUUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Cpu entity.
func (cuo *CPUUpdateOne) Save(ctx context.Context) (*Cpu, error) {
	var (
		err  error
		node *Cpu
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CPUMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CPUUpdateOne) SaveX(ctx context.Context) *Cpu {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CPUUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CPUUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CPUUpdateOne) sqlSave(ctx context.Context) (_node *Cpu, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cpu.Table,
			Columns: cpu.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cpu.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cpu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cpu.FieldID)
		for _, f := range fields {
			if !cpu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cpu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.VendorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldVendorID,
		})
	}
	if value, ok := cuo.mutation.Family(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldFamily,
		})
	}
	if value, ok := cuo.mutation.Model(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldModel,
		})
	}
	if value, ok := cuo.mutation.ModelName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cpu.FieldModelName,
		})
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: cpu.FieldCreatedAt,
		})
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: cpu.FieldUpdatedAt,
		})
	}
	if cuo.mutation.HostIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cpu.HostIDTable,
			Columns: []string{cpu.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.HostIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cpu.HostIDTable,
			Columns: []string{cpu.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Cpu{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cpu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
