// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jackc/pgtype"
	"github.com/menta2l/go-hwc/internal/data/ent/disk"
	"github.com/menta2l/go-hwc/internal/data/ent/host"
	"github.com/menta2l/go-hwc/internal/data/ent/predicate"
)

// DiskUpdate is the builder for updating Disk entities.
type DiskUpdate struct {
	config
	hooks    []Hook
	mutation *DiskMutation
}

// Where appends a list predicates to the DiskUpdate builder.
func (du *DiskUpdate) Where(ps ...predicate.Disk) *DiskUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetDevice sets the "device" field.
func (du *DiskUpdate) SetDevice(s string) *DiskUpdate {
	du.mutation.SetDevice(s)
	return du
}

// SetMount sets the "mount" field.
func (du *DiskUpdate) SetMount(s string) *DiskUpdate {
	du.mutation.SetMount(s)
	return du
}

// SetFsType sets the "fs_type" field.
func (du *DiskUpdate) SetFsType(s string) *DiskUpdate {
	du.mutation.SetFsType(s)
	return du
}

// SetOpts sets the "opts" field.
func (du *DiskUpdate) SetOpts(pa *pgtype.TextArray) *DiskUpdate {
	du.mutation.SetOpts(pa)
	return du
}

// SetCreatedAt sets the "created_at" field.
func (du *DiskUpdate) SetCreatedAt(t time.Time) *DiskUpdate {
	du.mutation.SetCreatedAt(t)
	return du
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (du *DiskUpdate) SetNillableCreatedAt(t *time.Time) *DiskUpdate {
	if t != nil {
		du.SetCreatedAt(*t)
	}
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DiskUpdate) SetUpdatedAt(t time.Time) *DiskUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (du *DiskUpdate) SetNillableUpdatedAt(t *time.Time) *DiskUpdate {
	if t != nil {
		du.SetUpdatedAt(*t)
	}
	return du
}

// SetHostIDID sets the "host_id" edge to the Host entity by ID.
func (du *DiskUpdate) SetHostIDID(id string) *DiskUpdate {
	du.mutation.SetHostIDID(id)
	return du
}

// SetHostID sets the "host_id" edge to the Host entity.
func (du *DiskUpdate) SetHostID(h *Host) *DiskUpdate {
	return du.SetHostIDID(h.ID)
}

// Mutation returns the DiskMutation object of the builder.
func (du *DiskUpdate) Mutation() *DiskMutation {
	return du.mutation
}

// ClearHostID clears the "host_id" edge to the Host entity.
func (du *DiskUpdate) ClearHostID() *DiskUpdate {
	du.mutation.ClearHostID()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DiskUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		if err = du.check(); err != nil {
			return 0, err
		}
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = du.check(); err != nil {
				return 0, err
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			if du.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DiskUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DiskUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DiskUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DiskUpdate) check() error {
	if _, ok := du.mutation.HostIDID(); du.mutation.HostIDCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Disk.host_id"`)
	}
	return nil
}

func (du *DiskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   disk.Table,
			Columns: disk.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: disk.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Device(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: disk.FieldDevice,
		})
	}
	if value, ok := du.mutation.Mount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: disk.FieldMount,
		})
	}
	if value, ok := du.mutation.FsType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: disk.FieldFsType,
		})
	}
	if value, ok := du.mutation.Opts(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: disk.FieldOpts,
		})
	}
	if value, ok := du.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: disk.FieldCreatedAt,
		})
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: disk.FieldUpdatedAt,
		})
	}
	if du.mutation.HostIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disk.HostIDTable,
			Columns: []string{disk.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.HostIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disk.HostIDTable,
			Columns: []string{disk.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{disk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// DiskUpdateOne is the builder for updating a single Disk entity.
type DiskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiskMutation
}

// SetDevice sets the "device" field.
func (duo *DiskUpdateOne) SetDevice(s string) *DiskUpdateOne {
	duo.mutation.SetDevice(s)
	return duo
}

// SetMount sets the "mount" field.
func (duo *DiskUpdateOne) SetMount(s string) *DiskUpdateOne {
	duo.mutation.SetMount(s)
	return duo
}

// SetFsType sets the "fs_type" field.
func (duo *DiskUpdateOne) SetFsType(s string) *DiskUpdateOne {
	duo.mutation.SetFsType(s)
	return duo
}

// SetOpts sets the "opts" field.
func (duo *DiskUpdateOne) SetOpts(pa *pgtype.TextArray) *DiskUpdateOne {
	duo.mutation.SetOpts(pa)
	return duo
}

// SetCreatedAt sets the "created_at" field.
func (duo *DiskUpdateOne) SetCreatedAt(t time.Time) *DiskUpdateOne {
	duo.mutation.SetCreatedAt(t)
	return duo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (duo *DiskUpdateOne) SetNillableCreatedAt(t *time.Time) *DiskUpdateOne {
	if t != nil {
		duo.SetCreatedAt(*t)
	}
	return duo
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DiskUpdateOne) SetUpdatedAt(t time.Time) *DiskUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (duo *DiskUpdateOne) SetNillableUpdatedAt(t *time.Time) *DiskUpdateOne {
	if t != nil {
		duo.SetUpdatedAt(*t)
	}
	return duo
}

// SetHostIDID sets the "host_id" edge to the Host entity by ID.
func (duo *DiskUpdateOne) SetHostIDID(id string) *DiskUpdateOne {
	duo.mutation.SetHostIDID(id)
	return duo
}

// SetHostID sets the "host_id" edge to the Host entity.
func (duo *DiskUpdateOne) SetHostID(h *Host) *DiskUpdateOne {
	return duo.SetHostIDID(h.ID)
}

// Mutation returns the DiskMutation object of the builder.
func (duo *DiskUpdateOne) Mutation() *DiskMutation {
	return duo.mutation
}

// ClearHostID clears the "host_id" edge to the Host entity.
func (duo *DiskUpdateOne) ClearHostID() *DiskUpdateOne {
	duo.mutation.ClearHostID()
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DiskUpdateOne) Select(field string, fields ...string) *DiskUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Disk entity.
func (duo *DiskUpdateOne) Save(ctx context.Context) (*Disk, error) {
	var (
		err  error
		node *Disk
	)
	if len(duo.hooks) == 0 {
		if err = duo.check(); err != nil {
			return nil, err
		}
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = duo.check(); err != nil {
				return nil, err
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			if duo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DiskUpdateOne) SaveX(ctx context.Context) *Disk {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DiskUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DiskUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DiskUpdateOne) check() error {
	if _, ok := duo.mutation.HostIDID(); duo.mutation.HostIDCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Disk.host_id"`)
	}
	return nil
}

func (duo *DiskUpdateOne) sqlSave(ctx context.Context) (_node *Disk, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   disk.Table,
			Columns: disk.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: disk.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Disk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, disk.FieldID)
		for _, f := range fields {
			if !disk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != disk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Device(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: disk.FieldDevice,
		})
	}
	if value, ok := duo.mutation.Mount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: disk.FieldMount,
		})
	}
	if value, ok := duo.mutation.FsType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: disk.FieldFsType,
		})
	}
	if value, ok := duo.mutation.Opts(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: disk.FieldOpts,
		})
	}
	if value, ok := duo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: disk.FieldCreatedAt,
		})
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: disk.FieldUpdatedAt,
		})
	}
	if duo.mutation.HostIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disk.HostIDTable,
			Columns: []string{disk.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.HostIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disk.HostIDTable,
			Columns: []string{disk.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Disk{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{disk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
