// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2l/go-hwc/internal/data/ent/host"
	"github.com/menta2l/go-hwc/internal/data/ent/netstat"
)

// NetstatCreate is the builder for creating a Netstat entity.
type NetstatCreate struct {
	config
	mutation *NetstatMutation
	hooks    []Hook
}

// SetAddr sets the "addr" field.
func (nc *NetstatCreate) SetAddr(s string) *NetstatCreate {
	nc.mutation.SetAddr(s)
	return nc
}

// SetPort sets the "port" field.
func (nc *NetstatCreate) SetPort(u uint64) *NetstatCreate {
	nc.mutation.SetPort(u)
	return nc
}

// SetProto sets the "proto" field.
func (nc *NetstatCreate) SetProto(s string) *NetstatCreate {
	nc.mutation.SetProto(s)
	return nc
}

// SetProcess sets the "process" field.
func (nc *NetstatCreate) SetProcess(s string) *NetstatCreate {
	nc.mutation.SetProcess(s)
	return nc
}

// SetCreatedAt sets the "created_at" field.
func (nc *NetstatCreate) SetCreatedAt(t time.Time) *NetstatCreate {
	nc.mutation.SetCreatedAt(t)
	return nc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nc *NetstatCreate) SetNillableCreatedAt(t *time.Time) *NetstatCreate {
	if t != nil {
		nc.SetCreatedAt(*t)
	}
	return nc
}

// SetUpdatedAt sets the "updated_at" field.
func (nc *NetstatCreate) SetUpdatedAt(t time.Time) *NetstatCreate {
	nc.mutation.SetUpdatedAt(t)
	return nc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nc *NetstatCreate) SetNillableUpdatedAt(t *time.Time) *NetstatCreate {
	if t != nil {
		nc.SetUpdatedAt(*t)
	}
	return nc
}

// SetHostIDID sets the "host_id" edge to the Host entity by ID.
func (nc *NetstatCreate) SetHostIDID(id string) *NetstatCreate {
	nc.mutation.SetHostIDID(id)
	return nc
}

// SetHostID sets the "host_id" edge to the Host entity.
func (nc *NetstatCreate) SetHostID(h *Host) *NetstatCreate {
	return nc.SetHostIDID(h.ID)
}

// Mutation returns the NetstatMutation object of the builder.
func (nc *NetstatCreate) Mutation() *NetstatMutation {
	return nc.mutation
}

// Save creates the Netstat in the database.
func (nc *NetstatCreate) Save(ctx context.Context) (*Netstat, error) {
	var (
		err  error
		node *Netstat
	)
	nc.defaults()
	if len(nc.hooks) == 0 {
		if err = nc.check(); err != nil {
			return nil, err
		}
		node, err = nc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NetstatMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nc.check(); err != nil {
				return nil, err
			}
			nc.mutation = mutation
			if node, err = nc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(nc.hooks) - 1; i >= 0; i-- {
			if nc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NetstatCreate) SaveX(ctx context.Context) *Netstat {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NetstatCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NetstatCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NetstatCreate) defaults() {
	if _, ok := nc.mutation.CreatedAt(); !ok {
		v := netstat.DefaultCreatedAt()
		nc.mutation.SetCreatedAt(v)
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		v := netstat.DefaultUpdatedAt()
		nc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NetstatCreate) check() error {
	if _, ok := nc.mutation.Addr(); !ok {
		return &ValidationError{Name: "addr", err: errors.New(`ent: missing required field "Netstat.addr"`)}
	}
	if _, ok := nc.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "Netstat.port"`)}
	}
	if _, ok := nc.mutation.Proto(); !ok {
		return &ValidationError{Name: "proto", err: errors.New(`ent: missing required field "Netstat.proto"`)}
	}
	if _, ok := nc.mutation.Process(); !ok {
		return &ValidationError{Name: "process", err: errors.New(`ent: missing required field "Netstat.process"`)}
	}
	if _, ok := nc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Netstat.created_at"`)}
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Netstat.updated_at"`)}
	}
	if _, ok := nc.mutation.HostIDID(); !ok {
		return &ValidationError{Name: "host_id", err: errors.New(`ent: missing required edge "Netstat.host_id"`)}
	}
	return nil
}

func (nc *NetstatCreate) sqlSave(ctx context.Context) (*Netstat, error) {
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (nc *NetstatCreate) createSpec() (*Netstat, *sqlgraph.CreateSpec) {
	var (
		_node = &Netstat{config: nc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: netstat.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: netstat.FieldID,
			},
		}
	)
	if value, ok := nc.mutation.Addr(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: netstat.FieldAddr,
		})
		_node.Addr = value
	}
	if value, ok := nc.mutation.Port(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: netstat.FieldPort,
		})
		_node.Port = value
	}
	if value, ok := nc.mutation.Proto(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: netstat.FieldProto,
		})
		_node.Proto = value
	}
	if value, ok := nc.mutation.Process(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: netstat.FieldProcess,
		})
		_node.Process = value
	}
	if value, ok := nc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: netstat.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := nc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: netstat.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := nc.mutation.HostIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   netstat.HostIDTable,
			Columns: []string{netstat.HostIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: host.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.host_netstat = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NetstatCreateBulk is the builder for creating many Netstat entities in bulk.
type NetstatCreateBulk struct {
	config
	builders []*NetstatCreate
}

// Save creates the Netstat entities in the database.
func (ncb *NetstatCreateBulk) Save(ctx context.Context) ([]*Netstat, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Netstat, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NetstatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NetstatCreateBulk) SaveX(ctx context.Context) []*Netstat {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NetstatCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NetstatCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}
