// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cpu is the predicate function for cpu builders.
type Cpu func(*sql.Selector)

// Disk is the predicate function for disk builders.
type Disk func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// Netstat is the predicate function for netstat builders.
type Netstat func(*sql.Selector)

// Network is the predicate function for network builders.
type Network func(*sql.Selector)
