// Code generated by entc, DO NOT EDIT.

package disk

import (
	"time"
)

const (
	// Label holds the string label denoting the disk type in the database.
	Label = "disk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDevice holds the string denoting the device field in the database.
	FieldDevice = "device"
	// FieldMountpoint holds the string denoting the mountpoint field in the database.
	FieldMountpoint = "mount"
	// FieldFstype holds the string denoting the fstype field in the database.
	FieldFstype = "fs_type"
	// FieldOpts holds the string denoting the opts field in the database.
	FieldOpts = "opts"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeHostID holds the string denoting the host_id edge name in mutations.
	EdgeHostID = "host_id"
	// Table holds the table name of the disk in the database.
	Table = "disks"
	// HostIDTable is the table that holds the host_id relation/edge.
	HostIDTable = "disks"
	// HostIDInverseTable is the table name for the Host entity.
	// It exists in this package in order to avoid circular dependency with the "host" package.
	HostIDInverseTable = "hosts"
	// HostIDColumn is the table column denoting the host_id relation/edge.
	HostIDColumn = "host_disk"
)

// Columns holds all SQL columns for disk fields.
var Columns = []string{
	FieldID,
	FieldDevice,
	FieldMountpoint,
	FieldFstype,
	FieldOpts,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "disks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"host_disk",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
