server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: pgx
    source: "postgresql://hwc:hwc@127.0.0.1:5432/hwc"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  server:
    addr: 0.0.0.0:9000
