// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/menta2l/go-hwc/internal/biz"
	"github.com/menta2l/go-hwc/internal/conf"
	"github.com/menta2l/go-hwc/internal/data"
	"github.com/menta2l/go-hwc/internal/server"
	"github.com/menta2l/go-hwc/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	hardwareRepo := data.NewHardwareRepo(dataData, logger)
	hardwareUsecase := biz.NewHardwareUsecase(hardwareRepo, logger)
	hardwareService := service.NewHardwareService(hardwareUsecase)
	httpServer := server.NewHTTPServer(confServer, hardwareService, logger)
	grpcServer := server.NewGRPCServer(confServer, hardwareService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
