// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/menta2l/go-hwc/internal/biz"
	"github.com/menta2l/go-hwc/internal/conf"
	"github.com/menta2l/go-hwc/internal/data"
	"github.com/menta2l/go-hwc/internal/worker"
)

// Injectors from wire.go:

func wireWorker(confData *conf.Data, logger log.Logger) (*worker.Worker, func(), error) {
	hardwareClient := data.NewHardwareServiceClient(confData)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	hardwareRepo := data.NewHardwareRepo(dataData, logger)
	hardwareUsecase := biz.NewHardwareUsecase(hardwareRepo, logger)
	workerWorker := worker.NewWorker(hardwareClient, logger, hardwareUsecase)
	return workerWorker, func() {
		cleanup()
	}, nil
}
